### ISSUE TITLE
Get Mac address garbled

### ISSUE THREAD

**Issue by qqJoker** [rqx110/SnmpSharpNet#10]
Hi,I found a problem when I used SnmpSharpNet in the WPF project. When I obtained the Mac address table of the switch, there would be a problem of garbled MAC address parsing, but I found that the returned data was not abnormal through Wireshark. Please help me, ths

**Comment by lextm** [comment]
In short, it is impossible for a library without MIB document parsing mechanism to know whether the data of an object is MAC address or not. That's why this library gives you a method to try,

https://github.com/rqx110/SnmpSharpNet/blob/master/Types/OctetString.cs#L312

**Comment by qqJoker** [comment]
Sorry I don't understand very well, "_data" in "OctetString" is my community, even using "ToMACAddressString" is invalid, because my community is not a Mac format string

**Comment by qqJoker** [comment]
> In short, it is impossible for a library without MIB document parsing mechanism to know whether the data of an object is MAC address or not. That's why this library gives you a method to try,
> 
> https://github.com/rqx110/SnmpSharpNet/blob/master/Types/OctetString.cs#L312

Sorry I don't understand very well, "_data" in "OctetString" is my community, even using "ToMACAddressString" is invalid, because my community is not a Mac format string

**Comment by qqJoker** [comment]
> In short, it is impossible for a library without MIB document parsing mechanism to know whether the data of an object is MAC address or not. That's why this library gives you a method to try,
> 
> https://github.com/rqx110/SnmpSharpNet/blob/master/Types/OctetString.cs#L312

My problem has been solved, thank you very much

**Comment by rqx110** [comment]
thanks @lextm
