### ISSUE TITLE
IPAddress Equality Check

### ISSUE THREAD

**Issue by jonnyb023** [rqx110/SnmpSharpNet#11]
https://github.com/rqx110/SnmpSharpNet/blob/25d2fbf2e132b904030db579fdf4a81333279755/SimpleSnmp.cs#L154

This should be changed to `if (_peerIP.Equals(IPAddress.None) || _peerIP.Equals(IPAddress.Any))` since `IPAddress` does not overload the `==` operator.

**Comment by rqx110** [comment]
While it would be better to change to this, but i will not change it right now. it is not effect the final result

**Comment by jonnyb023** [comment]
If you create a `SimpleSnmp` with a `string` IP address:

`var client = new SimpleSnmp("0.0.0.0");`

Then the `client.Valid` property would return `true`, when I think the intention of line 154 was to return `false`.

**Comment by rqx110** [comment]
ok, fix with https://github.com/rqx110/SnmpSharpNet/commit/1860d5bc5477f5de14df1c2c7b8bd3abddbf1c40

thanks @jonnyb023
