### ISSUE TITLE
Site https://www.snmpsharpnet.com/ is not reachable

### ISSUE THREAD

**Issue by ftamminga** [rqx110/SnmpSharpNet#3]
Luckily there is an archived version: https://web.archive.org/web/20170930133724/https://www.snmpsharpnet.com/

**Comment by rqx110** [comment]
it's http://www.snmpsharpnet.com/ not https://www.snmpsharpnet.com/

**Comment by ftamminga** [comment]
Then, maybe it’s a good idea to change that on this page https://github.com/rqx110/SnmpSharpNet?

Regards,
Frank
