### ISSUE TITLE
OctetString.Ishex is not reliable

### ISSUE THREAD

**Issue by norbert-olah** [rqx110/SnmpSharpNet#4]
Some devices return string that are not plain ASCII.
For example:  OID .1.3.6.1.2.1.25.3.2.1.3.1 (hrDeviceDescr) in my case contained the ® (registered trademark) character, and because of that, OctetString.ToString() returned hex data instead of a real string.

**Comment by lextm** [comment]
That's not something a library like SNMP#NET can solve for you merely based on the packet itself.

Keep in mind that OCTET STRING contains only raw bytes. Whether to interpret it as HEX or not, it depends on the actual MIB documents defining the objects. Complex types such as DisplayString, DateAndTime, MacAddress require extra decoding than what `ToString` can offer.

MIB document processing is not part of SNMP#NET, so you need to look at other products/libraries.

**Comment by norbert-olah** [comment]
Okay.
For now I've created a child class for OctetString which has a second ToString() function where I can set a flag to force the returned string to be hex or normal string.
I'm using SimpleSnmp class (as seen in the example) because I didn't want to dive deep into the protocoll, it looked good for the purpose.
Thank you for the response!
