### ISSUE TITLE
Support for AuthenticationDigests SHA-256 and SHA-512

### ISSUE THREAD

**Issue by Spy-Shifty** [rqx110/SnmpSharpNet#8]
It would be nice if the SHA-256 and SHA-512 AuthenticationDigests were supported for authentication.

**Comment by lextm** [comment]
You can easily write your own `IAuthenticationDigest` derived classes to fill the gaps. .NET has [System.Security.Cryptography.HMACSHA256](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha256?view=net-6.0) and [System.Security.Cryptography.HMACSHA512](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha512?view=net-6.0) for you.
