### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by JKissli** [rqx110/SnmpSharpNet#9]
Hi I wanted to know if this project is still maintained or if there is a successor  available?

Thanks for the Information

J

**Comment by qqJoker** [comment]
Hi,I found a problem when I used SnmpSharpNet in the WPF project. When I obtained the Mac address table of the switch, there would be a problem of garbled MAC address parsing, but I found that the returned data was not abnormal through Wireshark. What is the problem?

**Comment by lextm** [comment]
Ever since Milan Sinadinovic stopped working on this project in 2014 it has been out of maintenance. Luckily SNMP is also a standard that evolves no more, so you can continue to use this library for many typical SNMP tasks.

You can find commercial and open source alternatives from search engines.
